version: '3.8'

services:
  app:
    build: .
    container_name: your-bun-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    
  db:
    image: postgres:14-alpine
    container_name: your-db
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data: 