import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      <footer className="bg-[#CCCCCC] border-t-2 border-[#999999] p-4 ">
        <div className="font-bold max-w-4xl mx-auto text-center font-mono text-sm">
          <Link href="https://github.com/Makufff">
            <p>© 2025 Tanapat Chamted. All rights reserved.</p>
          </Link>
        </div>
      </footer>  
      </body>
      
    </html>
    
  );
}
